name: Push postservice

on:
  push:
    branches: 
    - main
    path:
    - "S3P2_project/AccountService/**"
    - ".github/workflows/push-accountservice.yml"

env:
  PROJECT_PATH: 'S3P2_project/AccountService/AccountService.csproj'

jobs:
  push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
      
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: 'S3P2_project/AccountService'
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/s3p2_accountBackend:latest
